[default_config]
version = "0.10.0"
assembler = "nasm"
instruction_set = "x86-64"

[default_config.opts]
compiler = "nasm" # or path to "nasm" if it isn't on your path
diagnostics = true
default_diagnostics = true
